### ISSUE TITLE
Documentation enhancements

### ISSUE THREAD

**Issue by scottweinert** [atomicfi/docs#1]
- [x] Replace webhook object & examples/params with actual design
- [x] Add table of test credentials for xDeposit product
- [x] Make "Products" section more clear & add image
- [ ] Add Transact demo & make link to iOS example work
- [x] Specify product (xdeposit or xbalance) during loading for Transact SDK
